name: horizontal_list_calendar
description: "A customizable horizontal list view calendar widget."
version: 0.0.1

homepage: https://github.com/nahidulislamshakin/flutter_horizontal_list_calendar.git
repository: https://github.com/nahidulislamshakin/flutter_horizontal_list_calendar.git
keywords:
  - horizontal
  - calendar
  - date picker
  - date selector
  - date scroll
  - horizontal list calendar
  - list
  - list calendar
  - Nahidul
  - Shakin
  - Nahidul Islam Shakin
  - nahidulislamshakin
  - flutter calendar
  - flutter
  - flutter horizontal calendar
  - custom horizontal calendar
  - custom calendar
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:


